### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by ghost** [amoussard/sftp-deployment#151]
path.js:7
The error was thrown from the SFTP-deployment package. You can help by creating an issue. Please explain what actions triggered this error.
Create issue on the SFTP-deployment package

**Comment by ghost** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.27.0 x64
**Electron**: 1.7.11
**OS**: Ubuntu 18.04
**Thrown From**: [SFTP-deployment](https://github.com/amoussard/sftp-deployment) package 1.0.2


### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at HTMLElement.DeploymentManager.uploadOnSave (/packages/SFTP-deployment/lib/DeploymentManager.js:228:27)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -6:45.8.0 core:save (input.hidden-input)
     -6:40.5.0 window:save-all (input.hidden-input)
     -6:20 tree-view:remove (div.icon.name.nuclide-ui-path-with-file-icon.icon-file-text.name.nuclide-file-tree-path)
     -6:14.1.0 tree-view:rename-selection (div.icon.name.nuclide-ui-path-with-file-icon.icon-file-text.name.nuclide-file-tree-path)
     -6:10.9.0 core:move-left (input.hidden-input)
     -6:09.9.0 core:backspace (input.hidden-input)
     -6:09.7.0 core:confirm (input.hidden-input)
     -3:48.8.0 nuclide-http-request-sender:send-http-request (input.hidden-input)
     -3:41 sftp-deployment:uploadSelection (div.icon.name.nuclide-ui-path-with-file-icon.icon-file-text.name.nuclide-file-tree-path)
     -3:19.4.0 tree-view:new-terminal-here-4 (div.)
     -2:01.0 find-and-replace:show (input.hidden-input)
  2x -1:58.6.0 core:backspace (input.hidden-input)
     -1:57.1.0 core:confirm (input.hidden-input)
  5x -1:45.6.0 core:backspace (input.hidden-input)
     -1:42.8.0 core:confirm (input.hidden-input)
     -1:21.3.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
android 0.1.0 
city-lights-ui 1.3.3 
ide-java 0.8.3 
nuclide 0.303.0 
platformio-ide-terminal 2.8.1 
react 0.18.0 
SFTP-deployment 1.0.2 
```
