### ISSUE TITLE
Cannot upload from Sidebar

### ISSUE THREAD

**Issue by smlombardi** [amoussard/sftp-deployment#30]
Select 1 or 2 files in sidebar, right-click & choose "FTP upload" andget this error:

```
Arguments to path.resolve must be strings TypeError: Arguments to path.resolve must be strings
  at Object.exports.resolve (path.js:327:15)
  at new PathScanner (/Applications/Atom.app/Contents/Resources/app/node_modules/scandal/lib/path-scanner.js:25:28)
  at Object.module.exports (/Applications/Atom.app/Contents/Resources/app/src/scan-handler.js:12:15)
  at process.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/task-bootstrap.js:84:10)
  at process.EventEmitter.emit (events.js:110:17)
  at handleMessage (child_process.js:323:10)
  at Pipe.channel.onread (child_process.js:351:11)

2Uncaught TypeError: Cannot read property 'getPath' of undefined 
```

Works fine when invoked from command palette

**Comment by amoussard** [comment]
Hi @smlombardi ,

Sorry for the long period of inactivity.

We are currently working on a new version : better code, more stable, and bug fixes.
This bug will be fixed at the next release.

Thank you for using our work ! :)

**Comment by amoussard** [comment]
Hi guys,

A new version (1.0.0) was published tonight.
Feel free to reopen if the problem is still there.

Enjoy ! :D
