### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory 'c:\Users\myUsername\AppData\Local\atom\app-0.176.0~.ssh\id_rsa'

### ISSUE THREAD

**Issue by ssnyder** [amoussard/sftp-deployment#46]
[Enter steps to reproduce below:]

1. select file from my project in tree view
2. right mouse button click - and select: FTP/SFTP Upload selection

File I chose is in the root of my project, and I'm not using ssh keys, so the id_rsa should not be used (see .ftpconfig for info)....plus the directory would be wrong anyway since I'm running this on windows and the ~ doesn't map to anything (unless I am using cygwin - which Atom is not).

.ftpconfig:
{
    "protocol": "sftp",
	"host": "myserver.name.com",
    "port": 22,
    "user": "username",
    "pass": "password",
    "remote": "~/deploy/tools",
	"connTimeout": 10000,
	"keepalive": 10000
}

**Atom Version**: 0.176.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [SFTP-deployment](git://github.com/amoussard/sftp-deployment) package, v0.5.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory 'c:\Users\sharon_snyder\AppData\Local\atom\app-0.176.0\~\.ssh\id_rsa'

```
At fs.js:455

Error: ENOENT, no such file or directory 'c:\Users\sharon_snyder\AppData\Local\atom\app-0.176.0\~\.ssh\id_rsa'
  at Error (native)
  at Object.fs.openSync (fs.js:455:18)
  at Object.module.(anonymous function) [as openSync] (c:\Users\sharon_snyder\AppData\Local\atom\app-0.176.0\resources\atom\common\lib\asar.js:422:20)
  at Object.fs.readFileSync (fs.js:313:15)
  at Object.fs.readFileSync (c:\Users\sharon_snyder\AppData\Local\atom\app-0.176.0\resources\atom\common\lib\asar.js:329:27)
  at SftpConfig.getConnectionInformations (c:\Users\sharon_snyder\.atom\packages\SFTP-deployment\lib\configs\SftpConfig.js:65:34)
  at SftpConnection.init (c:\Users\sharon_snyder\.atom\packages\SFTP-deployment\lib\connections\SftpConnection.js:54:39)
  at ConfigFactory.<anonymous> (c:\Users\sharon_snyder\.atom\packages\SFTP-deployment\lib\DeploymentManager.js:194:18)
  at ConfigFactory.emit (events.js:107:17)
  at c:\Users\sharon_snyder\.atom\packages\SFTP-deployment\lib\configs\ConfigFactory.js:70:10
  at fs.js:295:14
  at Object.oncomplete (fs.js:93:15)

```

### Commands

```
     -6:45.9 core:move-down (atom-text-editor.editor)
     -6:45.8 core:move-left (atom-text-editor.editor)
     -6:44.8 core:backspace (atom-text-editor.editor)
     -6:44.3 core:move-down (atom-text-editor.editor)
  2x -6:44.0 editor:move-to-first-character-of-line (atom-text-editor.editor)
     -6:41.1 core:move-down (atom-text-editor.editor)
     -6:40.7 core:move-left (atom-text-editor.editor)
     -6:40.3 core:move-right (atom-text-editor.editor)
  2x -6:39.0 core:move-down (atom-text-editor.editor)
     -6:36.7 core:save (atom-text-editor.editor)
     -6:29.1 core:close (atom-text-editor.editor)
     -6:23.9 sftp-deployment:uploadCurrentFile (atom-text-editor.editor)
  2x -4:37.9 core:delete (atom-text-editor.editor)
     -4:35.6 core:select-down (atom-text-editor.editor)
     -4:34.8 core:delete (atom-text-editor.editor)
     -4:28.0 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tualo-git-context"
    ],
    "themes": [
      "atom-dark-ui",
      "quantum-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.4.4
column-select, v0.1.0
cucumber, v0.4.1
git-log, v0.2.0
git-tab-status, v1.5.3
jenkins-dashboard, v0.2.0
language-gherkin, v0.3.0
language-gherkin-german, v0.5.2
language-rspec, v0.3.0
language-sql-mysql, v0.3.1
minimap, v4.1.3
open-in-atom, v0.1.8
open-last-project, v0.2.2
project-manager, v1.15.5
quantum-syntax, v0.2.1
Remote-FTP, v0.4.8
ruby-block-converter, v3.1.0
save-session, v0.11.5
ScssBundle, v0.4.0
select-rectangle, v1.0.2
seti-ui, vundefined
SFTP-deployment, v0.5.0
tabs-to-spaces, v0.8.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by alanhouser** [comment]
I have the same issue by taking the same steps as @ssnyder. 

[Enter steps to reproduce below:]

1. selected file from my project in tree view
2. right mouse button click - and selected: FTP/SFTP Upload selection

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [SFTP-deployment](git://github.com/amoussard/sftp-deployment) package, v0.5.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '~/.ssh/id_rsa'

```
At fs.js:574

Error: ENOENT, no such file or directory '~/.ssh/id_rsa'
  at Error (native)
  at Object.fs.openSync (fs.js:503:18)
  at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:118:20)
  at Object.fs.readFileSync (fs.js:355:15)
  at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:362:29)
  at SftpConfig.getConnectionInformations (/Users/alanhouser/.atom/packages/SFTP-deployment/lib/configs/SftpConfig.js:65:34)
  at SftpConnection.init (/Users/alanhouser/.atom/packages/SFTP-deployment/lib/connections/SftpConnection.js:54:39)
  at ConfigFactory.<anonymous> (/Users/alanhouser/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:199:18)
  at ConfigFactory.emit (events.js:116:17)
  at /Users/alanhouser/.atom/packages/SFTP-deployment/lib/configs/ConfigFactory.js:70:10
  at fs.js:337:14
  at FSReqWrap.oncomplete (fs.js:100:15)
  at EventEmitter.ipc.sendSync (/Users/alanhouser/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Users/alanhouser/Downloads/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Users/alanhouser/Downloads/Atom.app/Contents/Resources/app/src/context-menu-manager.js:172:33)
  at HTMLDocument.<anonymous> (/Users/alanhouser/Downloads/Atom.app/Contents/Resources/app/src/window-event-handler.js:153:33)
  at HTMLDocument.handler (/Users/alanhouser/Downloads/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Users/alanhouser/Downloads/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Users/alanhouser/Downloads/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
 15x -4:08.2 core:move-left (atom-text-editor.editor.mini)
     -4:06.5 core:backspace (atom-text-editor.editor.mini)
     -3:53.8 core:paste (atom-text-editor.editor.mini)
  9x -3:53.1 core:backspace (atom-text-editor.editor.mini)
 15x -3:50.0 core:move-left (atom-text-editor.editor.mini)
     -3:48.6 core:backspace (atom-text-editor.editor.mini)
     -3:47.9 core:confirm (atom-text-editor.editor.mini)
     -3:06.1 sftp-deployment:mapToRemote (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-atom-dark-ui)
  4x -1:36.4 core:backspace (atom-text-editor.editor)
     -1:27.1 snippets:next-tab-stop (atom-text-editor.editor)
     -1:27.1 snippets:expand (atom-text-editor.editor)
     -1:27.1 editor:indent (atom-text-editor.editor)
  2x -1:25.8 core:backspace (atom-text-editor.editor)
     -1:06.7 core:select-right (atom-text-editor.editor)
     -0:56.1 core:backspace (atom-text-editor.editor)
  2x -0:43.5 core:save (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "remote-edit"
    ]
  }
}
```

### Installed Packages

```coffee
# User
SFTP-deployment, v0.5.0
atom-alignment, v0.11.0
change-case, v0.5.1

# Dev
No dev packages
```

**Comment by amoussard** [comment]
Hi guys,

Sorry for the long period of inactivity.

We are currently working on a new version : better code, more stable, and bug fixes.
This bug will be fixed at the next release.

Thank you for using our work ! :)

**Comment by amoussard** [comment]
Hi guys,

A new version (1.0.0) was published tonight.
Feel free to reopen if the problem is still there.

Enjoy ! :D
