### ISSUE TITLE
Stopped working after not using for a few months with this project

### ISSUE THREAD

**Issue by Cipa** [amoussard/sftp-deployment#47]
[Enter steps to reproduce below:]

1. open project
2. right click on tab and "Upload current file"

I restarted atom, config file as not changed

**Atom Version**: 0.182.0
**System**: Mac OS X 10.10.2
**Thrown From**: [SFTP-deployment](git://github.com/amoussard/sftp-deployment) package, v0.5.0

### Stack Trace

Uncaught TypeError: Arguments to path.join must be strings

```
At path.js:472

TypeError: Arguments to path.join must be strings
  at Object.posix.join (path.js:472:13)
  at configurationFileExist (/Users/ciMac/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:61:18)
  at DeploymentManager.initConnection (/Users/ciMac/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:179:3)
  at atom-workspace.DeploymentManager.uploadCurrentFile (/Users/ciMac/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:220:8)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at [object Object].jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:74:67)
  at EventEmitter.emit (events.js:119:17)
  at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/Applications/Atom.app/Contents/Resources/atom/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/Applications/Atom.app/Contents/Resources/app/src/context-menu-manager.js:169:33)
  at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:147:33)
  at HTMLDocument.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "symbols-view",
      "close-tags",
      "key-peek",
      "less-autocompile",
      "preview",
      "red-wavy-underline",
      "language-objective-c",
      "language-csharp",
      "language-java",
      "language-perl",
      "language-ruby",
      "language-ruby-on-rails",
      "todo-show"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
SFTP-deployment, v0.5.0
Sublime-Style-Column-Selection, v1.2.3
atom-ctags, v2.6.0
autoclose-html, v0.15.0
emmet, v2.3.3
highlight-selected, v0.9.0
html-entities, v0.3.1
linter, v0.11.1
linter-csslint, v0.0.11
linter-jshint, v0.1.0
linter-less, v0.3.1
linter-php, v0.0.11
white-cursor, v0.5.2

# Dev
No dev packages
```

**Comment by Pooky** [comment]
Try this fix: https://github.com/amoussard/sftp-deployment/issues/48#issuecomment-77888316
Meaby it will help.

**Comment by Cipa** [comment]
it helped

**Comment by amoussard** [comment]
Hi guys,

Sorry for the long period of inactivity.

We are currently working on a new version : better code, more stable, and bug fixes.
This bug will be fixed at the next release.

Thank you for using our work ! :)

**Comment by amoussard** [comment]
Hi guys,

A new version (1.0.0) was published tonight.
Feel free to reopen if the problem is still there.

Enjoy ! :D
