### ISSUE TITLE
path must be a string

### ISSUE THREAD

**Issue by SeibelStan** [amoussard/sftp-deployment#50]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: linux 3.13.0-37-generic
**Thrown From**: [SFTP-deployment](git://github.com/amoussard/sftp-deployment) package, v0.5.0

### Stack Trace

Uncaught TypeError: path must be a string

```
At ATOM_SHELL_ASAR.js:50

TypeError: path must be a string
  at TypeError (native)
  at fs.lstatSync (fs.js:797:18)
  at Object.fs.lstatSync (ATOM_SHELL_ASAR.js:170:16)
  at FileManager.manageNextFile (/home/ss/.atom/packages/SFTP-deployment/lib/filesystem/FileManager.js:51:10)
  at FileManager.getSelection (/home/ss/.atom/packages/SFTP-deployment/lib/filesystem/FileManager.js:101:8)
  at DeploymentManager.connectionReady (/home/ss/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:294:18)
  at DeploymentManager.emit (events.js:138:20)
  at FtpConnection.<anonymous> (/home/ss/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:196:14)
  at FtpConnection.emit (events.js:113:17)
  at [object Object].<anonymous> (/home/ss/.atom/packages/SFTP-deployment/lib/connections/FtpConnection.js:53:10)
  at [object Object].emit (events.js:113:17)
  at Object.reentry [as cb] (/home/ss/.atom/packages/SFTP-deployment/node_modules/ftp/lib/connection.js:246:14)
  at Parser.<anonymous> (/home/ss/.atom/packages/SFTP-deployment/node_modules/ftp/lib/connection.js:117:20)
  at Parser.emit (events.js:119:17)
  at Parser._write (/home/ss/.atom/packages/SFTP-deployment/node_modules/ftp/lib/parser.js:58:10)
  at doWrite (_stream_writable.js:303:12)
  at writeOrBuffer (_stream_writable.js:290:5)
  at Parser.Writable.write (_stream_writable.js:219:11)
  at Socket.ondata (/home/ss/.atom/packages/SFTP-deployment/node_modules/ftp/lib/connection.js:281:20)
  at Socket.emit (events.js:116:17)
  at readableAddChunk (_stream_readable.js:164:16)
  at Socket.Readable.push (_stream_readable.js:127:10)
  at TCP.onread (net.js:530:20)

```

### Commands

```
  3x -0:09.6 core:backspace (atom-text-editor.editor)
     -0:08.5 project-manager:toggle (atom-text-editor.editor)
  2x -0:07.1 core:backspace (atom-text-editor.editor.mini)
     -0:06.1 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-objective-c",
      "language-go",
      "language-clojure"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
SFTP-deployment, v0.5.0
emmet, v2.3.4
minimap, v4.6.0
monokai, v0.12.0
project-manager, v1.15.5
script, v2.18.0

# Dev
No dev packages
```

**Comment by Pooky** [comment]
Did you upload file from tree view? Or tab context menu?

**Comment by amoussard** [comment]
Hi guys,

Sorry for the long period of inactivity.

We are currently working on a new version : better code, more stable, and bug fixes.
This bug will be fixed at the next release.

Thank you for using our work ! :)

**Comment by amoussard** [comment]
Hi guys,

A new version (1.0.0) was published tonight.
Feel free to reopen if the problem is still there.

Enjoy ! :D

**Comment by denniskuligin** [comment]
Duplicate of #118 #116 #113 #107 #100 #97
