### ISSUE TITLE
Uncaught TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by joshmarinacci** [amoussard/sftp-deployment#52]
I was able to successfully log into my server and edit a file, but when I tried to save the file I got this error.

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.3
**Thrown From**: [SFTP-deployment](https://github.com/amoussard/sftp-deployment) package, v1.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At /Users/josh/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:228

TypeError: Cannot read property 'path' of undefined
  at atom-workspace.DeploymentManager.uploadOnSave (/Users/josh/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:228:40)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:242:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:521:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:180:20)

```

### Commands

```
  2x -0:45.1 core:move-up (atom-text-editor.editor.is-focused)
  4x -0:44.1 editor:cut-to-end-of-line (atom-text-editor.editor.is-focused)
 12x -0:42.7 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:37.1 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
  4x -0:35.0 editor:cut-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:32.6 core:move-down (atom-text-editor.editor.is-focused)
  2x -0:29.6 editor:cut-to-end-of-line (atom-text-editor.editor.is-focused)
     -0:28.9 core:move-up (atom-text-editor.editor.is-focused)
     -0:28.7 editor:move-to-end-of-line (atom-text-editor.editor.is-focused)
 38x -0:28.0 core:move-left (atom-text-editor.editor.is-focused)
  7x -0:18.9 core:move-right (atom-text-editor.editor.is-focused)
 12x -0:15.7 core:delete (atom-text-editor.editor.is-focused)
  9x -0:05.1 core:backspace (atom-text-editor.editor.is-focused)
     -0:04.0 core:paste (atom-text-editor.editor.is-focused)
  4x -0:03.5 core:delete (atom-text-editor.editor.is-focused)
     -0:00.8 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "solarized-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
SFTP-deployment, v1.0.0
autoclose-html, v0.15.0
hex, v0.5.0
open-recent, v2.2.0
pretty-json, v0.3.2
remote-edit, v1.7.2

# Dev
No dev packages
```

**Comment by amoussard** [comment]
Hi @joshmarinacci ,

How have you created/opened your project ?
Can I have screenshot of your tree-view at the moment of the error ?

**Comment by nickmoline** [comment]
Happens to me if I move a tab outside of the project window and then attempt to save the file in that tab

Stack Trace
```
/Users/nick/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:228
TypeError: Cannot read property 'path' of undefined
    at atom-workspace.DeploymentManager.uploadOnSave (/Users/nick/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:228:40)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)
```

**Comment by JohnQUnknown** [comment]
Same here for me, I was trying to save a file and got the following:

1. Open a file from remote server
2. Modify contents
3. Try to save the file

**Atom Version**: 0.209.0
**System**: Microsoft Windows 10 Pro Insider Preview
**Thrown From**: [SFTP-deployment](https://github.com/amoussard/sftp-deployment) package, v1.0.0


### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At C:\Users\emili\.atom\packages\SFTP-deployment\lib\DeploymentManager.js:228

TypeError: Cannot read property 'path' of undefined
    at atom-workspace.DeploymentManager.uploadOnSave (C:\Users\emili\.atom\packages\SFTP-deployment\lib\DeploymentManager.js:228:40)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\emili\AppData\Local\atom\app-0.209.0\resources\app.asar\src\command-registry.js:238:29)
    at C:\Users\emili\AppData\Local\atom\app-0.209.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\emili\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:520:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\emili\AppData\Local\atom\app-0.209.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:355:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\emili\AppData\Local\atom\app-0.209.0\resources\app.asar\src\window-event-handler.js:177:20)
```

### Commands

```
     -2:39 editor:consolidate-selections (atom-text-editor.editor.mini)
     -2:38.7.0 core:cancel (atom-text-editor.editor.mini)
     -0:41.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "steam-pirate-ui",
      "one-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v2.0.4
emmet, v2.3.10
language-nginx, v0.5.3
minimap, v4.10.0
remote-edit, v1.8.2
SFTP-deployment, v1.0.0
steam-pirate-ui, v0.5.1

# Dev
No dev packages
```

**Comment by Shegl** [comment]
Also have this problem:

```TypeError: Cannot read property 'path' of undefined
    at atom-workspace.DeploymentManager.uploadOnSave (/Users/user/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:228:40)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/user/Downloads/Atom 2.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
    at /Users/user/Downloads/Atom 2.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/user/Downloads/Atom 2.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/user/Downloads/Atom 2.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Users/user/Downloads/Atom 2.app/Contents/Resources/app.asar/src/window-event-handler.js:180:20)```

System: MacOS Yosemite 10.10.4

**Comment by CoreySwish** [comment]
[Enter steps to reproduce below:]

1. opened file
2. edited
3. tried to save [command + s]
4. error

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.3
**Thrown From**: [SFTP-deployment](https://github.com/amoussard/sftp-deployment) package, v1.0.0


### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At /Users/coreybeaumont/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:228

TypeError: Cannot read property 'path' of undefined
    at atom-workspace.DeploymentManager.uploadOnSave (/Users/coreybeaumont/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:228:40)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/coreybeaumont/Downloads/Atom 2.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
    at /Users/coreybeaumont/Downloads/Atom 2.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/coreybeaumont/Downloads/Atom 2.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/coreybeaumont/Downloads/Atom 2.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Users/coreybeaumont/Downloads/Atom 2.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)
```

### Commands

```
     -0:24.7.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:24.3.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:24.3.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:20.5.0 core:move-to-bottom (atom-text-editor.editor.is-focused)
     -0:19.5.0 core:move-to-top (atom-text-editor.editor.is-focused)
  4x -0:18.9.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:16.1.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:15.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:14.2.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:13.8.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:12.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:12.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:08.3.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:08.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:08.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:00.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "SFTP-deployment": {}
}
```

### Installed Packages

```coffee
# User
SFTP-deployment, v1.0.0
emmet, v2.3.12
linter, v1.2.3
linter-bootlint, v0.0.6
linter-csslint, v0.0.14
linter-jshint, v1.0.4
linter-jsonlint, v0.1.4
linter-php, v0.0.15
minimap, v4.11.2
remote-edit, v1.8.10

# Dev
No dev packages
```

**Comment by amoussard** [comment]
Hi guys,

This issue is normally resolved.

**Comment by CoreySwish** [comment]
[Enter steps to reproduce below:]

1. updated to 1.0.2
2. restarted atom2
3. browser remote
4. opened
5. edited, save -> error.

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.3
**Thrown From**: [SFTP-deployment](https://github.com/amoussard/sftp-deployment) package, v1.0.2


### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At /Users/coreybeaumont/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:228

TypeError: Cannot read property 'path' of undefined
  at atom-workspace.DeploymentManager.uploadOnSave (/Users/coreybeaumont/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:228:40)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Users/coreybeaumont/Downloads/Atom 2.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Users/coreybeaumont/Downloads/Atom 2.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Users/coreybeaumont/Downloads/Atom 2.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Users/coreybeaumont/Downloads/Atom 2.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Users/coreybeaumont/Downloads/Atom 2.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -5:36.9.0 remote-edit:browse (atom-text-editor.editor.is-focused)
     -5:13.4.0 core:move-to-bottom (atom-text-editor.editor.is-focused)
  2x -5:12.9.0 core:move-up (atom-text-editor.editor.is-focused)
  5x -5:10.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -5:09.5.0 core:move-up (atom-text-editor.editor.is-focused)
     -5:08.9.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -5:08.9.0 editor:newline (atom-text-editor.editor.is-focused)
  5x -5:06.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -5:02.8.0 core:move-left (atom-text-editor.editor.is-focused)
  2x -5:01.8.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -4:57.9.0 core:move-right (atom-text-editor.editor.is-focused)
     -4:55.9.0 core:save (atom-text-editor.editor.is-focused)
     -3:52.5.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:01.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "SFTP-deployment": {}
}
```

### Installed Packages

```coffee
# User
SFTP-deployment, v1.0.2
emmet, v2.3.12
linter, v1.2.4
linter-bootlint, v0.0.6
linter-csslint, v0.0.14
linter-jshint, v1.1.4
linter-jsonlint, v0.1.4
linter-php, v1.0.2
minimap, v4.12.1
remote-edit, v1.8.14

# Dev
No dev packages
```

**Comment by rinkpijpker** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11.1
**Thrown From**: [SFTP-deployment](https://github.com/amoussard/sftp-deployment) package, v1.0.2


### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At /Users/rinkpijpker/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:229

TypeError: Cannot read property 'path' of undefined
  at atom-workspace.DeploymentManager.uploadOnSave (/Users/rinkpijpker/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:229:40)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -0:45.7.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:41.4.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:41.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:31.3.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:31.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:31.1.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:31.1.0 editor:newline (atom-text-editor.editor.is-focused)
  7x -0:27.3.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:20.6.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:20.6.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:16.8.0 core:paste (atom-text-editor.editor.is-focused)
  4x -0:15.4.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:14.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:14.2.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:14.2.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:03.7.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "nucleus-dark-ui",
      "batman-syntax"
    ],
    "disabledPackages": [
      "vim-mode"
    ]
  }
}
```

### Installed Packages

```coffee
# User
SFTP-deployment, v1.0.2
atom-beautify, v0.28.15
batman-syntax, v1.0.1
emmet, v2.3.13
file-type-icons, v0.7.3
linter, v1.9.1
minimap, v4.15.0
nucleus-dark-ui, v0.6.6
pigments, v0.18.1

# Dev
No dev packages
```

**Comment by mpandar** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [SFTP-deployment](https://github.com/amoussard/sftp-deployment) package, v1.0.2


### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At /Users/ipanda/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:229

TypeError: Cannot read property 'path' of undefined
    at atom-workspace.DeploymentManager.uploadOnSave (/Users/ipanda/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:229:40)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:11 core:move-down (atom-text-editor.editor.mini.is-focused)
     -1:08.2.0 hostview:edit (atom-text-editor.editor.mini.is-focused)
  4x -1:04.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:39.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:37.9.0 remote-edit:browse (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-solarized-light-syntax.theme-native-ui)
     -0:37.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:36.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -0:30.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  2x -0:29.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  5x -0:18.5.0 core:move-left (atom-text-editor.editor.is-focused)
  5x -0:16.7.0 core:select-right (atom-text-editor.editor.is-focused)
  2x -0:15.2.0 core:copy (atom-text-editor.editor.is-focused)
 10x -0:12.9.0 core:paste (atom-text-editor.editor.is-focused)
     -0:01.6.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "native-ui",
      "solarized-light-syntax"
    ],
    "disabledPackages": [
      "vim-mode"
    ]
  }
}
```

### Installed Packages

```coffee
# User
SFTP-deployment, v1.0.2
autocomplete-php, v0.3.7
emmet, v2.3.17
emmet-simplified, v2.5.0
emmet-snippets-compatibility, v1.0.1
language-babel, v2.6.2
language-blade, v0.16.0
language-ejs, v0.2.0
linter, v1.11.3
linter-php, v1.1.6
minimap, v4.18.4
native-ui, v0.11.0
php-integrator-autocomplete-plus, v0.3.0
php-integrator-base, v0.3.1
php-integrator-navigation, v0.2.4
pigments, v0.19.3
react, v0.12.10
remote-edit, v1.8.23
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by joshmweinstein** [comment]
[Enter steps to reproduce below:]

1. Browse remote server
2. Open file
3. Edit file
4. Save file

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: [SFTP-deployment](https://github.com/amoussard/sftp-deployment) package, v1.0.2


### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At /Users/joshweinstein/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:229

TypeError: Cannot read property 'path' of undefined
    at atom-workspace.DeploymentManager.uploadOnSave (/Users/joshweinstein/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:229:40)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -2:03.2.0 fuzzy-finder:toggle-git-status-finder (atom-text-editor.editor.is-focused)
     -2:00.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:59.9.0 remote-edit:browse (atom-text-editor.editor.is-focused)
  2x -1:58.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
  4x -1:57.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -1:01.2.0 core:paste (atom-text-editor.editor.is-focused)
  2x -0:19.1.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
SFTP-deployment, v1.0.2
emmet, v2.4.1
linter, v1.11.3
minimap, v4.19.0
remote-edit, v1.8.23
seti-ui, v0.8.1

# Dev
No dev packages
```

**Comment by Amstramgram** [comment]
0. window already open with project, tabs open and sftp config
1. open new window
2. open new file
3. add content
4. save (cmd + s)

**Atom Version**: 1.4.3
**System**: Mac OS X 10.11.3
**Thrown From**: [SFTP-deployment](https://github.com/amoussard/sftp-deployment) package, v1.0.2


### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At /Users/JulienMiclo/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:229

TypeError: Cannot read property 'path' of undefined
    at atom-workspace.DeploymentManager.uploadOnSave (/Users/JulienMiclo/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:229:40)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:00.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false,
    "closeEmptyWindows": false,
    "destroyEmptyPanes": false,
    "themes": [
      "one-dark-ui",
      "spacegray-atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
SFTP-deployment, v1.0.2
atom-jade, v0.3.0
auto-indent, v0.5.0
emmet, v2.4.1
file-watcher, v0.4.0
pigments, v0.23.0
sass-autocompile, v0.12.2
spacegray-atom-dark-syntax, v1.1.1
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by margonaut** [comment]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.7.1
**System**: Mac OS X 10.10.3
**Thrown From**: [SFTP-deployment](https://github.com/amoussard/sftp-deployment) package, v1.0.2


### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At /Users/Margaret/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:229

TypeError: Cannot read property 'path' of undefined
    at atom-workspace.DeploymentManager.uploadOnSave (/Users/Margaret/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:229:40)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -5:13.2.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  2x -5:07.1.0 remote-edit:browse (atom-text-editor.editor.mini.is-focused)
  2x -3:48.7.0 tree-view:toggle (atom-text-editor.editor.is-focused)
     -3:47.4.0 emmet:toggle-comment (atom-text-editor.editor.is-focused)
     -3:47.3.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -3:46.7.0 emmet:toggle-comment (atom-text-editor.editor.is-focused)
     -3:46.7.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -3:37.6.0 remote-edit:show-open-files (atom-text-editor.editor.is-focused)
     -3:31.4.0 remote-edit:browse (atom-text-editor.editor.is-focused)
     -2:39.1.0 fuzzy-finder:toggle-git-status-finder (atom-text-editor.editor.is-focused)
     -2:35.1.0 remote-edit:browse (atom-text-editor.editor.is-focused)
  3x -1:50.6.0 core:move-left (atom-text-editor.editor.is-focused)
  7x -1:50 core:select-right (atom-text-editor.editor.is-focused)
  2x -1:49.2.0 core:select-left (atom-text-editor.editor.is-focused)
     -1:48.2.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:47.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "erb-helper",
      "linter-erb",
      "Remote-FTP",
      "SFTP-deployment"
    ]
  }
}
```

### Installed Packages

```coffee
# User
SFTP-deployment, v1.0.2
emmet, v2.3.12
file-icons, v1.5.8
gist-it, v0.7.0
linter, v1.11.3
linter-ruby, v0.1.6
remote-edit, v1.8.24

# Dev
No dev packages
```

**Comment by TheBrenny** [comment]
My guess is that there needs to be a check for whether or not the file exists on [this line][https://github.com/amoussard/sftp-deployment/blob/master/lib/DeploymentManager.js#L250]. Or somehow change the event listener so it's fired _after_ the file is saved.

**Comment by benyanke** [comment]
This issue also occurs for me, in projects that I am not using the plugin for. How should I debug?

**Comment by jambway** [comment]
k

**Comment by ChristianFranke** [comment]
push!
