### ISSUE TITLE
Uncaught TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by dodekaeder** [amoussard/sftp-deployment#53]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.175.0
**System**: linux 3.16.0-4-amd64
**Thrown From**: [SFTP-deployment](https://github.com/amoussard/sftp-deployment) package, v1.0.0

### Stack Trace

Uncaught TypeError: Cannot read property 'length' of undefined

```
At /home/lippe/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:170

TypeError: Cannot read property 'length' of undefined
  at atom-workspace.DeploymentManager.generateConfigFile (/home/lippe/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:170:37)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/usr/share/atom/resources/app/node_modules/command-palette/lib/command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/usr/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/lib/select-list-view.js:335:21)
  at space-pen-div.atom.commands.add.core:confirm (/usr/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
     -0:05.3 command-palette:toggle (atom-pane.pane.active)
  2x -0:00.8 core:move-down (atom-text-editor.editor.mini)
     -0:00.2 core:confirm (atom-text-editor.editor.mini)
     -0:00.0 sftp-deployment:mapToRemote (atom-pane.pane.active)
```

### Config

```json
{
  "core": {
    "themes": [
      "isotopeTheme",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
isotopeTheme, v2.1.1
linter, v0.11.0
linter-jshint, v0.1.0
linter-jsl, v0.0.1
script, v2.16.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by dodekaeder** [comment]
tried to use sftp-deployment package

https://atom.io/packages/sftp-deployment

**Comment by amoussard** [comment]
Hi guys,

This issue is normally resolved.
