### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by marcoslhc** [amoussard/sftp-deployment#62]
[Enter steps to reproduce below:]

1. Select Upload Current File in context menu

**Atom Version**: 0.206.0
**System**: Mac OS X 10.10.3
**Thrown From**: [SFTP-deployment](https://github.com/amoussard/sftp-deployment) package, v1.0.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/marcoslh/.atom/packages/SFTP-deployment/lib/observers/MessageObserver.js:47

TypeError: undefined is not a function
  at showLoader (/Users/marcoslh/.atom/packages/SFTP-deployment/lib/observers/MessageObserver.js:47:21)
  at MessageObserver.notify (/Users/marcoslh/.atom/packages/SFTP-deployment/lib/observers/MessageObserver.js:73:13)
  at /Users/marcoslh/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:49:18
  at Array.forEach (native)
  at DeploymentManager.notifyObservers (/Users/marcoslh/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:48:20)
  at atom-workspace.DeploymentManager.uploadCurrentFile (/Users/marcoslh/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:215:10)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/command-registry.js:153:19)
  at [object Object].jQuery.fn.trigger (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
  at EventEmitter.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:75:67)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)
  at EventEmitter.ipc.sendSync (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)
  at BrowserWindow.RemoteMemberFunction [as emit] (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/context-menu-manager.js:170:31)
  at HTMLDocument.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:148:33)
  at HTMLDocument.handler (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
  2x -2:02.6.0 core:save (atom-text-editor.editor.is-focused)
     -1:40.5.0 core:close (atom-text-editor.editor.is-focused)
     -1:39.2.0 symbols-view:toggle-file-symbols (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-isotope-ui)
     -1:38.5.0 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-isotope-ui)
     -1:34.4.0 editor:move-to-first-character-of-line (atom-text-editor.editor.mini.is-focused)
     -1:32.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -1:29.7.0 core:save (atom-text-editor.editor.is-focused)
     -0:57.9.0 core:close (atom-text-editor.editor.is-focused)
     -0:54.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:53.9.0 core:close (atom-text-editor.editor.is-focused)
     -0:49.8.0 settings-view:open (atom-workspace.workspace.scrollbars-visible-always.theme-base16-tomorrow-dark-theme.theme-isotope-ui)
     -0:17.9.0 fuzzy-finder:toggle-file-finder (ul.list-inline.tab-bar.inset-panel)
     -0:15.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:14.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:12.8.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -0:11.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "isotope-ui",
      "base16-tomorrow-dark-theme"
    ]
  },
  "SFTP-deployment": {}
}
```

### Installed Packages

```coffee
# User
SFTP-deployment, v1.0.0
atom-django, v0.3.0
color-picker, v2.0.4
django-templates, v0.5.0
editorconfig, v1.0.0
emmet, v2.3.10
git-log, v0.4.1
git-tab-status, v1.9.2
isotope-ui, v2.4.0
linter, v0.12.6
linter-flake8, v1.4.2
linter-jscs, v1.12.0
linter-jshint, v0.1.6
linter-python-pep8, v0.2.0
node-debugger, v1.0.5
pigments, v0.4.4

# Dev
No dev packages
```

**Comment by charle-s** [comment]
Hi, 
I use this plugins for 2 months without problem but since some  days i have the same problem than you: "Uncaught TypeError: undefined is not a function".

Atom version : 0.207.0
Thrown From: SFTP-deployment package, v1.0.0

Someone kown a solution at this probleme ?

Thanks in advance, 

Charles

**Comment by christ0ph3r** [comment]
Hi,

I used this plugin fine for months as well.  Now this error occurs.

**Comment by dvogt23** [comment]
+1

**Comment by kupoback** [comment]
I'm getting the same issue as you all.

I am running 0.208.0

Anyone have any idea how to correct this, or an alternative to an SFTP upload?

**Comment by marcoslhc** [comment]
Now I'm using https://atom.io/packages/remote-sync Don't have the time to
fix and propose a PR right now and I'm way to comfy with atom to change
editor

*Saludos…*

*Marcos Luis Hernández*
~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~ ~

1151, Fairlake Tr. #1716.
Weston, FL. 33326

[*website*]: *http://xiryvella.com/ <http://xiryvella.com/>*
[*github*]: *https://github.com/marcoslhc* <https://github.com/marcoslhc>
[*twitter*]: @marcoslhc <http://twitter.com/marcoslhc>
[*mobile*]: +1 954 300 9924
[*info*]: *https://www.google.com/profiles/marcoslhc
<https://www.google.com/profiles/marcoslhc>*

**Comment by grubin1989** [comment]
+1

**Comment by rafaelstz** [comment]
:+1:

**Comment by bradleyflood** [comment]
+1

**Comment by udokmeci** [comment]
```js
var atomModule = require('atom');
atomModule.$
undefined
```

Undefinied is `atomModule.$`

**Comment by tuberiumf** [comment]
I fixed this, and send pull request to author

**Comment by amoussard** [comment]
Hi guys,
This issue is fixed.
Thank you all and especially @tuberiumf :)
