### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by DSigmund** [amoussard/sftp-deployment#68]
C:\Users\sigmundd\.atom\packages\SFTP-deployment\lib\observers\MessageObserver.js:47  

TypeError: undefined is not a function
    at showLoader (C:\Users\sigmundd\.atom\packages\SFTP-deployment\lib\observers\MessageObserver.js:47:21)
    at MessageObserver.notify (C:\Users\sigmundd\.atom\packages\SFTP-deployment\lib\observers\MessageObserver.js:73:13)
    at C:\Users\sigmundd\.atom\packages\SFTP-deployment\lib\DeploymentManager.js:49:18
    at Array.forEach (native)
    at DeploymentManager.notifyObservers (C:\Users\sigmundd\.atom\packages\SFTP-deployment\lib\DeploymentManager.js:48:20)
    at atom-workspace.DeploymentManager.uploadCurrentFile (C:\Users\sigmundd\.atom\packages\SFTP-deployment\lib\DeploymentManager.js:215:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\sigmundd\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:241:29)
    at CommandRegistry.handleCommandEvent (C:\Users\sigmundd\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\sigmundd\AppData\Local\atom\app-1.0.0\resources\app.asar\src\command-registry.js:156:19)
    at EventEmitter.<anonymous> (C:\Users\sigmundd\AppData\Local\atom\app-1.0.0\resources\app.asar\src\window-event-handler.js:70:30)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:166:7)

**Comment by codycoder** [comment]
I have the same issue: /Users/rob/.atom/packages/SFTP-deployment/lib/observers/MessageObserver.js:47

**Comment by alanhouser** [comment]
Ditto —when right-clicking on project root folder and selecting "download selection"

/Users/alanhouser/.atom/packages/SFTP-deployment/lib/observers/MessageObserver.js:47

TypeError: undefined is not a function
    at showLoader (/Users/alanhouser/.atom/packages/SFTP-deployment/lib/observers/MessageObserver.js:47:21)
    at MessageObserver.notify (/Users/alanhouser/.atom/packages/SFTP-deployment/lib/observers/MessageObserver.js:73:13)
    at /Users/alanhouser/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:49:18
    at Array.forEach (native)
    at DeploymentManager.notifyObservers (/Users/alanhouser/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:48:20)
    at atom.confirm.buttons.Overwrite (/Users/alanhouser/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:289:22)
    at Atom.module.exports.Atom.confirm (/Applications/Atom.app/Contents/Resources/app.asar/src/atom.js:735:49)
    at atom-workspace.DeploymentManager.downloadSelection (/Users/alanhouser/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:285:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:156:19)
    at jQuery.fn.trigger (/Applications/Atom.app/Contents/Resources/app.asar/src/space-pen-extensions.js:64:23)
    at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:75:67)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:169:7)
    at EventEmitter.ipc.sendSync (/Applications/Atom.app/Contents/Resources/atom.asar/renderer/api/lib/ipc.js:21:31)

**Comment by motionland** [comment]
The same issue here too! -- Thanks

**Comment by vsnote** [comment]
How to solve

**Comment by alanhouser** [comment]
I just cleared everything out and set it up again; got the same error when trying to "Download Selection".

**Comment by alessiodionisi** [comment]
Same error...

**Comment by dst89** [comment]
same :(

**Comment by rafaelstz** [comment]
Same :disappointed:

**Comment by DKMonster** [comment]
same :(

**Comment by voodoo144** [comment]
the same issue

**Comment by CoreySwish** [comment]
+1

**Comment by jbbrwcky** [comment]
+1

**Comment by pvtmashkov** [comment]
+1

**Comment by tony-garcia** [comment]
this bug has to do with changes to the Atom 1.0 API described [here](https://atom.io/docs/v0.204.0/upgrading-to-1-0-apis-upgrading-your-package). I issued a pull request where you can see the [changes](https://github.com/tony-garcia/sftp-deployment/commit/013402ed4cb054e6be981e65b06c6f3da10e2044)

**Comment by JeffShomali** [comment]
+1

**Comment by bbg-rdorsey** [comment]
+1

**Comment by igormilla** [comment]
+1

**Comment by bradleyflood** [comment]
+1

**Comment by amoussard** [comment]
Hi guys,

This issues is fixed.
