### ISSUE TITLE
Failed to activate the SFTP-deployment package

### ISSUE THREAD

**Issue by adamsir** [amoussard/sftp-deployment#86]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [SFTP-deployment](https://github.com/amoussard/sftp-deployment) package, v1.0.2

### Stack Trace

Failed to activate the SFTP-deployment package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/Users/adamsir/.atom/packages/SFTP-deployment/lib/sftp-deployment.js:12:23)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:245:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:838:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:226:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -1:51.6.0 tree-view:toggle (atom-text-editor.editor.is-focused)
     -1:48.2.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:42.9.0 core:close (atom-text-editor.editor.is-focused)
     -0:37.9.0 editor:newline-below (atom-text-editor.editor.is-focused)
     -0:36.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:33.5.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -0:31.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:31.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  4x -0:21.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:12.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  4x -0:09.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:04.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:04.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:03.3.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -0:02.5.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:01.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
SFTP-deployment, v1.0.2

# Dev
No dev packages
```

**Comment by amoussard** [comment]
Hi @adamsir,

The problem is still there since updates ?

Thank you for your feedback.
