### ISSUE TITLE
cannot upload sftp after latest atom update

### ISSUE THREAD

**Issue by lightinen** [amoussard/sftp-deployment#88]
Atom v.1.0.19
OS Win10x64

Trace:
Error: Cannot find module 'ssh2'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\Стас\AppData\Local\atom\app-1.0.19\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Стас\.atom\packages\SFTP-deployment\lib\connections\SftpConnection.js:8:21)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (C:\Users\Стас\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\Стас\.atom\packages\SFTP-deployment\lib\connections\ConnectionFactory.js:7:22)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .js] (C:\Users\Стас\AppData\Local\atom\app-1.0.19\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)

**Comment by amoussard** [comment]
Hi @lightinen,

I will take a look, but it's an old post, maybe it's fixed since updates.

Thank you for your feedback.
