### ISSUE TITLE
Can't save file

### ISSUE THREAD

**Issue by ksb86** [amoussard/sftp-deployment#90]
If I open Atom by itself (no files, folders or projects), a new blank unsaved file window opens.  If I enter text and try to save that file, I get an error and cannot save the file.

[Enter steps to reproduce below:]

1. Open Atom
2. Type text in new window
3. Command+S

**Atom Version**: 1.0.19
**System**: Mac OS X 10.10.5
**Thrown From**: [SFTP-deployment](https://github.com/amoussard/sftp-deployment) package, v1.0.2

### Stack Trace

Uncaught TypeError: Cannot read property 'path' of undefined

```
At /Users/me/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:229

TypeError: Cannot read property 'path' of undefined
    at atom-workspace.DeploymentManager.uploadOnSave (/Users/me/.atom/packages/SFTP-deployment/lib/DeploymentManager.js:229:40)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:245:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)
```

### Commands

```
     -0:00.6.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "packagesWithKeymapsDisabled": [
      "turbo-javascript"
    ],
    "disabledPackages": [
      "autosave"
    ]
  },
  "SFTP-deployment": {
    "uploadOnSave": false
  }
}
```

### Installed Packages

```coffee
# User
SFTP-deployment, v1.0.2
color-picker, v2.0.12
ctrl-last-tab, v0.2.0
emmet, v2.3.12
grunt-runner, v0.11.0
hex, vundefined
jquery-snippets, v11.0.0
pigments, v0.15.0
project-manager, v2.5.2
set-syntax, v0.3.0

# Dev
No dev packages
```

**Comment by tukhfatov** [comment]
Same issue

**Comment by amoussard** [comment]
Hi @ksb86 @tukhfatov,

I will take a look and fix it in the next release.

Thank you for using my package.
