### ISSUE TITLE
Same..

### ISSUE THREAD

**Issue by XEngine** [amoussard/sftp-deployment#96]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Mac OS X 10.11.1
**Thrown From**: [SFTP-deployment](https://github.com/amoussard/sftp-deployment) package, v1.0.2

### Stack Trace

Uncaught TypeError: Cannot read property 'on' of undefined

```
At /Users/cem/.atom/packages/sftp-deployment/lib/connections/SftpConnection.js:66

TypeError: Cannot read property 'on' of undefined
  at /Users/cem/.atom/packages/sftp-deployment/lib/connections/SftpConnection.js:66:23
  at /Users/cem/.atom/packages/sftp-deployment/node_modules/ssh2/lib/client.js:1228:14
  at SSH2Stream.<anonymous> (/Users/cem/.atom/packages/sftp-deployment/node_modules/ssh2/lib/Channel.js:181:24)
  at emitNone (events.js:67:13)
  at SSH2Stream.emit (events.js:166:7)
  at parsePacket (/Users/cem/.atom/packages/sftp-deployment/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:3230:10)
  at SSH2Stream._transform (/Users/cem/.atom/packages/sftp-deployment/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:555:13)
  at SSH2Stream.Transform._read [as __read] (_stream_transform.js:167:10)
  at SSH2Stream._read (/Users/cem/.atom/packages/sftp-deployment/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:213:15)
  at SSH2Stream.Transform._write (_stream_transform.js:155:12)
  at doWrite (_stream_writable.js:291:12)
  at writeOrBuffer (_stream_writable.js:277:5)
  at SSH2Stream.Writable.write (_stream_writable.js:206:11)
  at Socket.ondata (_stream_readable.js:521:20)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at TCP.onread (net.js:520:20)

```

### Commands

```
     -2:27.6.0 sftp-deployment:downloadSelection (span.name.icon.icon-file-text)
  6x -1:15.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:09.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -1:08.3.0 core:save (atom-text-editor.editor.is-focused)
     -1:00.5.0 sftp-deployment:uploadSelection (li.file.entry.list-item.selected)
     -0:47.6.0 core:close (atom-text-editor.editor.is-focused)
     -0:39.9.0 sftp-deployment:downloadSelection (li.file.entry.list-item.selected)
     -0:24.5.0 core:cancel (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
  2x -0:17.7.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:16.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:15.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:11.1.0 sftp-deployment:downloadSelection (span.name.icon.icon-file-text)
     -0:06.0 sftp-deployment:uploadSelection (span.name.icon.icon-file-text)
```

### Config

```json
{
  "core": {
    "themes": [
      "native-ui",
      "one-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
SFTP-deployment, v1.0.2
file-icons, v1.6.11
minimap, v4.16.0
native-ui, v0.6.0

# Dev
No dev packages
```

**Comment by amoussard** [comment]
Hi @XEngine,

I will take a look and fix it in the next release.

Thank you for your feedback.
